# Change these first
owner: sudoblockio # Your GitHub organization or username, where this repository lives
repo: substrate-status-page # The name of this repository

sites:
  - name: US WEST Polkadot RPC Endpoints
    url: https://polkadot-us-west-2.geometry.io/api
    method: POST
    headers:
          - "Content-Type: application/json; charset=utf-8"
    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
  - name: US WEST Polkadot WS Endpoints
    url: wss://polkadot-us-west-2.geometry.io/websocket
    check: "ws"
    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
    maxResponseTime: 10000
  - name: US WEST Kusama RPC Endpoints
    url: https://kusama-us-west-2.geometry.io/api
    method: POST
    headers:
          - "Content-Type: application/json; charset=utf-8"
    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
  - name: US WEST Kusama WS Endpoints
    url: wss://kusama-us-west-2.geometry.io/websocket
    check: "ws"
    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
    maxResponseTime: 10000

#  - name: EU WEST Polkadot RPC Endpoints
#    url: https://polkadot-eu-west-1.geometry.io/api
#    method: POST
#    headers:
#          - "Content-Type: application/json; charset=utf-8"
#    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
#  - name: EU WEST Polkadot WS Endpoints
#    url: wss://polkadot-eu-west-1.geometry.io/websocket
#    check: "ws"
#    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
#    maxResponseTime: 10000
#  - name: EU WEST Kusama RPC Endpoints
#    url: https://kusama-eu-west-1.geometry.io/api
#    method: POST
#    headers:
#          - "Content-Type: application/json; charset=utf-8"
#    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
#  - name: EU WEST Kusama WS Endpoints
#    url: wss://kusama-eu-west-1.geometry.io/websocket
#    check: "ws"
#    data: { "jsonrpc":"2.0", "method":"system_health", "params":[],"id":1 }
#    maxResponseTime: 10000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.substrate.sudoblock.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/sudoblockio/substrate-status-page/master/assets/geometry-logo.png
  name: Status Page
  introTitle: "**Polkadot and Kusama Status Page**"
  introMessage: "Endpoints deployed by **Geometry Labs** supported by grants the Web3 Foundation."
  navbar:
    - title: Status
      href: /
    - title: Kibana
      href: https://kibana.us-west-2.aws.geometry.io/app/dashboards#/view/3b6f9ad0-fc82-11eb-9d99-658467b44c78
    - title: Telemetry
      href: http://telemetry.substrate.geometry.io/
#    - title: Grafana
#      href: https://grafana.substrate.geometry.io
    - title: GitHub
      href: https://github.com/$OWNER/substrate-meta

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
